// src/components/layout/Footer.tsx
export default function Footer() {
    return (
      <footer className="bg-secondary-100 text-center dark:bg-secondary-600">
        <div className="bg-secondary-200 p-4 text-center text-secondary-700 dark:bg-secondary-700 dark:text-secondary-200">
          © 2023 Copyright 
          <span className="text-secondary-800 dark:text-secondary-400"> Nick Mackowski</span>
        </div>
      </footer>
    );
  };

// components/Footer.vue
<!-- Taken from https://tailwind-elements.com/docs/standard/navigation/footer/ -->

<template>
  <footer class="bg-secondary-100 text-center dark:bg-secondary-600">
    <!-- <div class="grid justify-center">
      <SignUpForm />
      <div class="ml-embedded" data-form="nCLwlb"></div>
    </div> -->
    <!--Copyright section-->
    <div
      class="bg-secondary-200 p-4 text-center text-secondary-700 dark:bg-secondary-700 dark:text-secondary-200"
    >
      © 2023 Copyright
      <a class="text-secondary-800 dark:text-secondary-400">Nick Mackowski</a>
    </div>
  </footer>
</template>
